USE master;
GO
DROP DATABASE IF EXISTS Univercity;
GO

CREATE DATABASE Univercity
COLLATE Cyrillic_General_CS_AS;
  
GO
USE Univercity;
GO
CREATE TABLE tbSpec(
	Id INT IDENTITY NOT NULL,
	Name NVARCHAR(32) NOT NULL,
	PRIMARY KEY (Id)
);
CREATE TABLE tbGroups(
	Id INT IDENTITY NOT NULL, 
	Name NVARCHAR (32) NOT NULL,
	SpecId INT NOT NULL,
	PRIMARY KEY (Id),
	FOREIGN KEY (SpecId) REFERENCES tbSpec (Id)
);
CREATE TABLE tbStudents(
	Id INT IDENTITY NOT NULL, 
	FirstName NVARCHAR (64) NOT NULL,
	MiddleName NVARCHAR (64) NOT NULL,
	LastName NVARCHAR (64) NOT NULL,
	Birthday DATE NOT NULL,
	LogbookNumber INT NULL,
	Email NVARCHAR(260) NOT NULL,
	Address NVARCHAR(260) NULL,
	GroupId INT NULL,
	CONSTRAINT ST_PK PRIMARY KEY (Id), 
	CONSTRAINT ST_GR_FK FOREIGN KEY (GroupId)
	REFERENCES tbGroups (Id)
	ON DELETE SET NULL ON UPDATE CASCADE,
	CONSTRAINT UNIQ_1 UNIQUE (Email)
);
CREATE TABLE tbPhones(
	Id INT IDENTITY NOT NULL,
	Phone NVARCHAR(32) NOT NULL,
	StudentId INT NOT NULL,
	CONSTRAINT PH_PK PRIMARY KEY (Id), 
	CONSTRAINT PH_ST_FK FOREIGN KEY (StudentId)
	REFERENCES tbStudents (Id)
	ON DELETE CASCADE ON UPDATE CASCADE,
	UNIQUE (Phone)
);

CREATE TABLE tbTeachers(
	Id INT IDENTITY NOT NULL,
	FirstName NVARCHAR (64) NOT NULL,
	MiddleName NVARCHAR (64) NOT NULL,
	LastName NVARCHAR (64) NOT NULL
);

ALTER TABLE tbTeachers ADD PRIMARY KEY(Id);

CREATE TABLE tbDepartments(
	Id INT IDENTITY,
	Name NVARCHAR(32) NOT NULL
);
ALTER TABLE tbDepartments ADD CONSTRAINT PK_DEP PRIMARY KEY (Id);
ALTER TABLE tbTeachers ADD DepId INT NULL;
ALTER TABLE tbTeachers ADD FOREIGN KEY (DepId) REFERENCES tbDepartments(Id)
ON DELETE SET NULL ON UPDATE CASCADE;

CREATE TABLE tbSubjects(
	Id INT IDENTITY,
	Name NVARCHAR(260) NOT NULL
);
ALTER TABLE tbSubjects ADD PRIMARY KEY (Id);

CREATE TABLE tbTeachSubj(
	Id INT IDENTITY PRIMARY KEY,
	TeachId INT NOT NULL,
	SubjId INT NOT NULL,
	FOREIGN KEY (TeachId) REFERENCES tbTeachers(Id) 
	ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (SubjId) REFERENCES tbSubjects(Id) 
	ON DELETE CASCADE ON UPDATE CASCADE,
	UNIQUE (TeachId, SubjId)
);

CREATE TABLE tbMarks(
	Id INT IDENTITY,
	Mark INT NOT NULL,
	TSId INT NOT NULL,
	StudId INT NOT NULL,
	PRIMARY KEY(Id),
	FOREIGN KEY(StudId) REFERENCES tbStudents(Id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(TSId) REFERENCES tbTeachSubj(Id),
	CHECK (Mark BETWEEN 1 AND 12)
);
